spring.application.name=emd_dept

spring.datasource.url=jdbc:mysql://localhost:3306/emp_dptm
spring.datasource.driver-Class-Name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Tilesh@1722
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dtilesh@gmail.com
spring.mail.password=rcfw agxe zyiy tmqa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
